---
DatabaseAddress: "mongodb+srv://cluster0.z4ms5.mongodb.net/myFirstDatabase?authSource=%24external&authMechanism=MONGODB-X509&retryWrites=true&w=majority&tlsCertificateKeyFile=certs/db.pem"
DatabaseName: "url_shortener"
CacheAddress: "localhost:6379"
